spring.application.name=s14backend

# Aiven MySQL Cloud Connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Twilio Credentials
twilio.account.sid=${TWILIO_ACCOUNT_SID:AC_PLACEHOLDER}
twilio.auth.token=${TWILIO_AUTH_TOKEN:TOKEN_PLACEHOLDER}
twilio.phone.number=${TWILIO_PHONE_NUMBER:+1000000000}
